### PR TITLE
Made location selector searchable

### PR DESCRIPTION
**Pull request by techlab23**
- Updated location selector on home page to load all affected countries and made the dropdown 
   searchable. 
- Fix: Overflow-x on opened location selector dropdown.

### CODE REVIEW

**Comment by xming13** [comment]
Hi @techlab23 there is some issue with the styling when scrolled
image

**Comment by techlab23** [comment]
Could you let me know which browser and version did you use ?
I have tested this on safari, chrome, firefox and it looks okay.

**Comment by xming13** [comment]
@techlab23 It is on chrome browser Version 80.0.3987.132 on macbook pro.
It happens when the country list is scrolled to the right when the country dropdown is opened and the country list is visible.

**Comment by techlab23** [comment]
> @techlab23 long country name will be truncated and will not be fully visible if the container is not scrollable.

@xming13  Okay, I have updated list container to use flex and made long country names to show up on 
                     next lines, without affecting the Flag size.  
Please see below - 

Screen Shot 2020-03-22 at 5 19 03 pm

**Pull request merged**
