### PR TITLE
Shorten translation keys and fallback to English when translation is not available

### PR DESCRIPTION
**Pull request by victor-ac**
- [x] Use English translation if a resource string key for another language is not found (vue-i18n)
- [x] Shorten translation keys for English
- [x] Adjust components markup to use the new keys
- [ ] Adjust other language translations according to the changes made to the English resource file
- [x] Incorporate new translations that were merged since this branch was created

### CODE REVIEW

**Comment by victor-ac** [comment]
@xming13 and @gibtang, I've modified the translation files in English to shorten the translation keys, fallback to the English translation if there's no translation and reuse existing keys. However, as translations are coming really fast, I have some catch up to do with the latest changes. Can we freeze changes on translations for 1 or 2 days to allow me to complete this work? Otherwise, conflicts will be very frequent and will make it difficult to merge this.

@gibtang I also noticed that you created a script to help with translations, so I'm guessing that'd need to be updated as well. Can you take on that?

**Comment by xming13** [comment]
Hi @victor-ac, currently the translation files (e.g. lang/ja.js) are generated from the google sheet. I think you should add a new column for the translation key in the google sheet to keep track of the translation key in use. All lang/*.js should be generated by script when there is an update.

**Comment by victor-ac** [comment]
Hi @xming13, really? :(  Is the script the one responsible for commit ed859ea? If so, it undid the a lot of the Portuguese translation and I suspect it had a similar impact on other translation files as well.

Is there a chance of updating the files directly using this PR and then use the script to make updates from then on?

**Comment by xming13** [comment]
Hi @victor-ac, we can manually port the translation to the google sheet. Most translators are not familiar with technical stuff, and uses google sheet to do translation so we will use the google sheet as the source of truth for translation.

**Comment by victor-ac** [comment]
Yeah, I understand @xming13. In this case, is it guaranteed the translations aren't going to be lost again when the script is ran? If so, I can port the Portuguese translation and shorten the keys there. Can you or Gibson explain how these translations are incorporated back to the codebase? Since the keys will be shortened, I'll need to add a column to the spreadsheet with their new names, so that we can continue mapping the translation entries to the keys. Thanks!

**Comment by xming13** [comment]
Hi @victor-ac, we export google sheet into csv file by clicking "File > Download > csv" from the google sheet menu, place the exported csv in `scripts/translation-json-generator` and run `sh scripts/translation-json-generator/run.sh`. All the source code is in `scripts/translation-json-generator` folder. Basically it parses the google sheet and generate `{locale}.js`. We can update the script to read the shorten key column and generate the output we want. Translated text will be based on the values in the google sheet.

**Comment by xming13** [comment]
Hi @victor-ac, I have added a column for the translated key in google sheet and updated the script to generate `{locales}.js`. Can you give it a try and let me know if there is any issue? Some of the text do not have proper translated key yet and need to cross check with what's used in `.vue` files

**Comment by xming13** [comment]
Hi @victor-ac, I have ported Portuguese translation to google sheet.

**Pull request merged**
