### PR TITLE
Adding translation for Brazilian Portuguese (pt-br)

### PR DESCRIPTION
**Pull request by victor-ac**
* Fixing a few translation issues as well (missing/incorrect keys)

### CODE REVIEW

**Comment by victor-ac** [comment]
@xming13 can you review this PR? Also, if there are tickets you want contribution on, please add them as Issues, I'd be glad to help.

**Comment by xming13** [comment]
@victor-ac Thanks. It has been merged to dev and staging branch, currently pending QA before it goes live.

**Comment by victor-ac** [comment]
Thanks, good to know. It would be good if a CONTRIBUTE.MD file would outline that process. I was thinking the PR hadn't been reviewed yet :)

**Comment by xming13** [comment]
@victor-ac good idea. In the meanwhile, there are new text pending translation in the latest `dev` branch. Appreciate if you can help with the translation.

**Comment by victor-ac** [comment]
@xming13  Will do. Should I be merging changes to the `dev` branch on this repo instead of `master` going forward? I'll push a patch tomorrow with the new set of translation 👍

**Comment by xming13** [comment]
@victor-ac Yes, please open pull request to `dev` branch instead of `master` branch. Thanks :)

**Comment by victor-ac** [comment]
Closing this PR, since I'll open a new one merging changes from a dev-based branch to dev (instead of master).

**Pull request closed without merging**
